### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [dasstoni/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by dasstoni** [comment]
I added this line inside my <head> tag in my application.html.erb file:
<meta name="viewport" content="width=device-width, initial-scale=1">

-Is this the correct tag and location to put it?

**Comment by dasstoni** [comment]
I added this line "<meta name="viewport" content="width=device-width, initial-scale=1">" to my head tag in my application file.

Is this the correct tag and location to put it?

**Comment by dasstoni** [comment]
I added this line: 
`<meta name="viewport" content="width=device-width, initial-scale=1">`
to my head tag in my application file.

Is this the correct tag and location to put it?

**Comment by BillyMassey** [comment]
Yep and Yep! :) Good Job 👍
